platform :ios, 9.0
use_frameworks!

target 'WQPackage_Example' do
  pod 'WQPackage', :path => '../'
#  pod 'Moya'
  pod 'Moya/RxSwift'
#  pod 'RxSwift'
  pod 'RxCocoa'
#  pod 'Alamofire'
#  pod 'RxAlamofire'
#  pod 'PromiseKit'
  target 'WQPackage_Tests' do
    inherit! :search_paths

    
  end
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'RxSwift'
        target.build_configurations.each do |config|
          if config.name == 'Debug'
            config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
          end
        end
      end
    end
  end
  
end
